-d D:\docs\ostim\digital\gowin\uart_simple\impl\gwsynthesis\uart_simple.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\docs\ostim\digital\gowin\uart_simple\src\uart_simple.cst
-cfg D:\docs\ostim\digital\gowin\uart_simple\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
