-d D:\docs\ostim\digital\gowin\uart_copilot\impl\gwsynthesis\uart_copilot.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-UV9QN88PC6/I5
-cst D:\docs\ostim\digital\gowin\uart_copilot\src\uart_copilot.cst
-cfg D:\docs\ostim\digital\gowin\uart_copilot\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
